version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: akeron_postgres
    environment:
      POSTGRES_USER: akeron_user
      POSTGRES_PASSWORD: shqiperia_e_lire_1912
      POSTGRES_DB: akeron_tours
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
